---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: df7854c892e3/web:<TAG>
        imagePullPolicy: Always
        name: web

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: pipeline-demo
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
