apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: df7854c892e3/web:<TAG>
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: LoadBalancer
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
